Make distinction between vested and unvested shares
vacuumlabs/pay-overview pull request #62
Opened 2020-09-20 13:27 UTC by mondejka

- add column vested
- share balance calculator separates vested and unvested balances

2020-09-20 20:23 UTC, darjanin requested changes

2020-09-20 20:23 UTC, darjanin commented on client/src/api.js
> +
Please remove this as we should use the `date-fns` that get's the today's date.

2020-09-20 20:23 UTC, darjanin commented on client/src/pages/SharesPage.js
> +      Total: totalBalance,
Name of keys should start with lowercase letter. Don't change it to uppercase to get better name presented in the UI. Better way would be to have all texts in own translation object, but for this case using lodash's `capitalize`  function would be enough.

2020-09-20 20:23 UTC, darjanin commented on client/src/pages/SharesPage.js
> +    const totalBalance = vestedBalance + unvestedBalance
The _balance_ is not needed in here, as it doesn't add more clarity to naming. It makes it harder to read.

2020-09-20 20:23 UTC, darjanin commented on client/src/pages/SharesPage.js
> +    const sumShares = (data) => _.sum(data.map((v) => v.amount))
As we are using a lot of _lodash_ functions, instead of this own function we should use `sumBy`.
It doesn't make the expression longer in way that it would matter, but it's more clearer which field is required to calculate the balance of _vestedShares_. And we don't need to come up with other name to explain what we are doing.

```js
const vested = sumShares(vestedShares)
// vs
const vested = _.sumBy(vestedShares, 'amount')
```

2020-09-20 20:23 UTC, darjanin commented on client/src/pages/SharesPage.js
> +    const today = new Date()
As mentioned above, we don't want to work with dates directly if we can avoid it. Having the library for them loaded in the project is good reason to use it.

2020-09-20 20:23 UTC, darjanin commented on client/src/pages/SharesPage.js
> +  }
I used here `isFuture` as it behaves in opposite way to the `item.vesting_date < today`. There is function `isPast` but it behaves as `item.vesting_date <= today`.

2020-09-20 20:23 UTC, darjanin commented on client/src/pages/SharesPage.js
> +          }
```suggestion
          <dl style={{display: 'flex', flexWrap: 'wrap'}}>
            {Object.entries(balances).map(([key, balance]) => (
              <div className={classes.balance} key={key} style={{display: 'flex'}}>
                <dt className={classes.title}>{_.capitalize(key)}:</dt>
                <dd><span className={classes.number}>{balance}</span> shares</dd>
              </div>
            ))}
          </dl>
```

This way it's less spread through the UI and connected as one information.
The `dl` is semantic element for having some terms with values for each of them.

2020-09-21 08:53 UTC, darjanin approved these changes

2020-09-21 08:59 UTC, mondejka commented on client/src/pages/SharesPage.js
> +  }
Thanks, didn't notice the library. It's much better this way.

2020-09-21 09:07 UTC, mondejka commented on client/src/pages/SharesPage.js
> +          }
Yes, it makes much more sense this way.

2020-09-21 09:40 UTC, mlenik approved these changes

2020-09-21 09:41 UTC, merged